"""changed distance column name

Revision ID: 2c429bb93433
Revises: 210179403793
Create Date: 2022-04-29 12:05:31.517149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c429bb93433'
down_revision = '210179403793'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('dist_from_earth_in_million_km', sa.Integer(), nullable=True))
    op.drop_column('planet', 'dist_from_earth')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('dist_from_earth', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('planet', 'dist_from_earth_in_million_km')
    # ### end Alembic commands ###
